services:
  # Backend API service
  - type: web
    name: portfolio-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.cjs
    plan: free
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    
  # Frontend static site
  - type: web
    name: cheera-udaykiran
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
